[project]
name = "mlfsm"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = "3.11.*"
numpy = "2.0.*"
scipy = "1.13.*"
networkx = "3.2.*"
ase = "3.25.*"
geometric = "1.1.*"
pytest = "*"
pytest-cov = ">=4.0.0"
pip = "*"
ruff = "*"
mypy = "*"
pre-commit = "*"

[tasks]
fmt = "ruff format ."
lint = "ruff check ."
types = "mypy mlfsm/"
test = "pytest"
